number1=int(input("enter number1:"))
number2=int(input("enter number2:"))
print("maximum :",max(number1,number2))
print("minimum :",min(number1,number2))
print("average :",(number1+number2)/2)
print("addition :",(number1+number2))
print("multipication :",(number1*number2))