n1=int(input("enter number1:"))
n2=int(input("enter number2:"))
print("maximum :",max(n1,n2))
print("minimum :",min(n1,n2))
print("average :",(n1+n2)/2)
print("addition :",(n1+n2))
print("multipication :",(n1*n2))