# Input to the script will be a tuple with bike names : ("pulsar", "duke", "shine")
Bike_Names = ("pulsar", "duke", "shine")
Total_Items = len(Bike_Names)
print("The total number of items in Bike_Names are",Total_Items)
print("The index number for \"shine\" in the tuple is", Bike_Names.index("shine"))
Bike_Names_List = list(Bike_Names)
Bike_Names_List.append("splendor")
Bike_Names = tuple(Bike_Names_List)
print("The modified Bike List is",Bike_Names)
Bike_Names_List = list(Bike_Names)
Bike_Names_List.remove("duke")
Bike_Names = tuple(Bike_Names_List)
print("The modified Bike List after removing duke is",Bike_Names)
