a=40
b=30
maximum=max(a,b)
print('maximum of two numbers=',maximum)
a=50
b=20
minimum=min(a,b)
print('mininum of two numbers=',minimum)
a=20
b=30
avg=(a+b)/2
print("Average two numbers = %.2f"%avg)
a=10
b=30
print('addtion of two numbers=',a+b)
a=50
b=30
print('multiplication of two numbers=',a*b)