input1= int(input("enter the value of a :"))
input2= int(input("enter the value of b :"))
print(input1)
print(input2)
print("addition of 2 intergers : ", input1+input2)
print("multiplication of 2 intergers : ",input1*input2)
print("Average of 2 integers :", (input1+input2)/2)
print("maximum number :", max(input1,input2))
print("minimum number :", min(input1,input2))