# What is zen of python? Write a program to illustrate "zen of python"? (Hint : Search on google.)
print("What is zen of python?")
print("The Zen of Python is a collection of 19 guiding principles for writing computer programs that influence the design of the Python programming language.[1] Software engineer Tim Peters wrote this set of principles and posted it on the Python mailing list in 1999.[2] Peters's list left open a 20th principle for Guido to fill in , referring to Guido van Rossum, the original author of the Python language. The vacancy for a 20th principle has not been filled.")
print("The principals of zen of python are")
print("1. Beautiful is better than ugly.")
print("2. Explicit is better than implicit.")
print("3. Simple is better than complex.")
print("4. Complex is better than complicated.")
print("5. Flat is better than nested.")
print("6. Sparse is better than dense.")
print("7. Readability counts.")
print("8. Special cases aren't special enough to break the rules.")
print("9. Although practicality beats purity.")
print("10. Errors should never pass silently.")
print("11. Unless explicitly silenced.")
print("12. In the face of ambiguity, refuse the temptation to guess.")
print("13. There should be one-- and preferably only one --obvious way to do it.")
print("14. Although that way may not be obvious at first unless you're Dutch.")
print("15. Now is better than never.")
print("16. Although never is often better than *right* now.")
print("17. If the implementation is hard to explain, it's a bad idea.")
print("18. If the implementation is easy to explain, it may be a good idea.")
print("19. Namespaces are one honking great idea -- let's do more of those!")